image: Visual Studio 2017

install:
  - choco install gitversion.portable -pre -y

before_build:
  - dotnet restore src/DataDock.sln
  - ps: gitversion /l console /output buildserver /updateassemblyinfo

configuration: Release

build_script:
  - dotnet build -c Release src/DataDock.sln

test_script:
  - ps: |
      foreach ($test in ls src/*.Tests) {
        Push-Location $test
        echo "build: Testing project in $test"
        $testlog = $test.Name + ".log"
        dotnet test -c %CONFIGURATION% -l "trx;logfilename=$testlog" -r .
        Push-AppveyorArtifact $testlog
        if($LASTEXITCODE -ne 0) { $host.SetShouldExit($LastExitCode) }
        Pop-Location
      }
      
after_test:
  - docker build -t datadock/web -t datadock/web:%GitVersion_SemVer% docker/web
  - docker build -t datadock/worker -t datadock/worker:%GitVersion_SemVer% docker/worker
      

artifacts:
  - path: 'src\*.Tests\*.trx'

