image: Visual Studio 2017

install:
  - choco install gitversion.portable -pre -y

before_build:
  - dotnet restore src/DataDock.sln
  - ps: gitversion /l console /output buildserver /updateassemblyinfo

configuration: Release

build_script:
  - dotnet build -c Release src/DataDock.sln

test_script:
  - ps: |
      foreach ($test in ls src/*.Tests) {
        Push-Location $test
        echo "build: Testing project in $test"
        $testlog = $test + ".log"
        dotnet xunit -configuration %CONFIGURATION% -notrait "Category=explicit" | Out-File $testlog
        Push-AppveyorArtifact $testlog
        if($LASTEXITCODE -ne 0) { exit 3 }
        Pop-Location
      }

artifacts:
  - path: 'src\*.Tests\*.log'

