image: ubuntu

environment:
  nodejs_version: "8.12.0"
  DOCKER_USER:
    secure: 9LU4zEJHdpb+7UcFHNyvQQ==
  DOCKER_PASS:
    secure: SpDXXy2IWz1XFdorgWZcNWfmUze0KkAOeZQNnzWtZ7I=

services:
  - docker

install:
  - wget https://github.com/GitTools/GitVersion/releases/download/5.1.1/gitversion-linux-5.1.1.tar.gz
  - tar -zxf gitversion-linux-5.1.1.tar.gz
  - sh: nvm install $nodejs_version

before_build:
  - sh: |
      dotnet restore src/DataDock.sln
      GitVersion/GitVersion /l console /output buildserver
      echo GitVersion Full: $GitVersion_FullSemVer
      echo GitVersion NuGet: $GitVersion_NuGetVersion
      npm install --global gulp-cli karma-cli

configuration: Release

build_script:
  - sh: dotnet build -c Release src/DataDock.sln
  - sh: msbuild /t:BuildImages /p:Tag=$GitVersion_FullSemVer build.proj 

test_script:
  - dotnet test -c Release src/DataDock.Common.Tests
  - dotnet test -c Release src/DataDock.Web.Tests
  - dotnet test -c Release src/DataDock.Worker.Tests
  - pushd src/DataDock.Web
  - karma start karma.conf.js --single-run 
  - popd

deploy_script:
  - sh: |
      if [ "$APPVEYOR_REPO_TAG" == "true" ]; then
        docker login -u=$DOCKER_USER -p=$DOCKER_PASS
        docker push datadock/web:$GitVersion_FullSemVer
        docker push datadock/web:latest
        docker push datadock/worker:$GitVersion_FullSemVer
        docker push datadock/worker:latest
      elif [ "$APPVEYOR_REPO_BRANCH" == "develop" ]; then
        docker login -u=$DOCKER_USER -p=$DOCKER_PASS
        docker push datadock/web:$GitVersion_FullSemVer
        docker push datadock/worker:$GitVersion_FullSemVer
      else
        echo "Deployment will only run on a tag or commit to master"
      fi
