version: '3.4'

services:
  elasticsearch:
    image: elasticsearch
    volumes:
      - es-data-1:/home/elastic/data
      - es-logs-1:/home/elastic/logs
      - es-backup:/home/elastic/backup
    build:
      context: ../src/Elasticsearch
      dockerfile: Dockerfile

  datadock.web:
    image: datadock.web
    depends_on:
      - elasticsearch
    volumes:
      - dd-files:/datadock
    build:
      context: web
      dockerfile: Dockerfile

  datadock.worker:
    image: datadock.worker
    depends_on:
      - elasticsearch
    volumes:
      - dd-files:/datadock
    environment:
      GITHUB_HEADER: dev-datadock-io
    build:
      context: worker
      dockerfile: Dockerfile

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.2.2
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200/

volumes:
  dd-files:
  es-data-1:
  es-logs-1:
  es-backup: