version: '3.4'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.5.1
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - path.repo=/usr/share/elasticsearch/backup
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data-1:/usr/share/elasticsearch/data
      - es-logs-1:/usr/share/elasticsearch/logs
      - es-backup:/usr/share/elasticsearch/backup

  web:
    image: datadock/web
    depends_on:
      - elasticsearch
    build:
      context: web
      dockerfile: Dockerfile

  worker:
    image: datadock/worker
    depends_on:
      - elasticsearch
    environment:
      GITHUB_HEADER: dev-datadock-io
    build:
      context: worker
      dockerfile: Dockerfile

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.5.1
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200/

volumes:
  es-data-1:
  es-logs-1:
  es-backup: