version: '3.4'

services:
  worker:
    environment:
      - DD_ENVIRONMENT=Development

  web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:80"

  elasticsearch:
    ports:
      - "9200:9200"
