version: '3.4'

services:
  datadock.worker:
    environment:
      - DD_ENVIRONMENT=Development

  datadock.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "5000:80"

  elasticsearch:
    ports:
      - "9200:9200"
