version: '3.4'

services:
  datadock.web:
    image: datadock.web
    volumes:
      - dd-files:/datadock
    build:
      context: .
      dockerfile: DataDock.Web/Dockerfile

  datadock.worker:
    image: datadock.worker
    volumes:
      - dd-files:/datadock
    environment:
      GITHUB_HEADER: dev-datadock-io
    build:
      context: .
      dockerfile: DataDock.Worker/Dockerfile

  elasticsearch:
    image: elasticsearch
    volumes:
      - es-data-1:/home/elastic/data
      - es-logs-1:/home/elastic/logs
      - es-backup:/home/elastic/backup
    build:
      context: Elasticsearch
      dockerfile: Dockerfile

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.2.2
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200/
    ports:
      - "5601:5601"

volumes:
  dd-files:
  es-data-1:
  es-logs-1:
  es-backup:
