name: DataDock Build and Test

on:
  push:
    branches:
    - develop
    - feature/gh-actions
  pull_request:
    branches: [ develop ]

jobs:
  import-ui:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./src/DataDock.ImportUI
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '16'

    - name: Install
      run: npm ci

    - name: Lint
      run: npm run lint -- --no-fix
 
    - name: Unit Tests
      run: npm run test:unit
      
  core:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '16'
    - name: Restore Packages
      run: dotnet restore src/DataDock.sln
    - name: Build
      run: dotnet build -c Release src/DataDock.sln
    - name: Common tests
      run: dotnet test -c Release src/DataDock.Common.Tests
    - name: Web tests
      run: dotnet test -c Release src/DataDock.Web.Tests
    - name: Worker tests
      run: dotnet test -c Release src/DataDock.Worker.Tests
