name: DataDock Build and Test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the develop branch
on:
  push:
    branches:
    - develop
  pull_request:
    branches: [ develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./src/DataDock.ImportUI
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '10'

    - name: Install
      run: npm ci

    - name: Lint
      run: npm run lint -- --no-fix
 
    - name: Unit Tests
      run: npm run test:unit
